# Optional: pip install pre-commit && pre-commit install
repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        exclude: package-lock.json|.*\.lock|\.next/|node_modules/
