const fs = require('fs');
const http = require('http');
const path = require('path');

/** Canonical FastAPI port for this repo (Compose `backend` publishes 8000:8000). */
const PORT = 8000;
const ENV_PATH = path.join(__dirname, '..', 'frontend', '.env.local');

function checkHealth(port) {
  return new Promise((resolve) => {
    const opts = {
      hostname: '127.0.0.1',
      port,
      path: '/api/health',
      method: 'GET',
      timeout: 2000,
    };
    const req = http.request(opts, (res) => {
      res.resume();
      resolve(res.statusCode === 200);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => {
      req.destroy();
      resolve(false);
    });
    req.setTimeout(2000);
    req.end();
  });
}

(async () => {
  if (await checkHealth(PORT)) {
    const base = `http://127.0.0.1:${PORT}`;
    const snippet = `\n# Auto-generated by scripts/detect-backend.js — remove if managed manually\nNEXT_PUBLIC_API_URL=${base}\nCHAT_BACKEND_URL=${base}/api/v1/chat\nTTS_BACKEND_URL=${base}/api/v1/tts-with-timing\n`;
    fs.writeFileSync(ENV_PATH, snippet, { flag: 'a' });
    console.log(`✅ FastAPI responded on ${base}/api/health — appended backend URLs to frontend/.env.local`);
    return;
  }
  console.log(
    `❌ No OK /api/health at http://127.0.0.1:${PORT} — start the backend on port ${PORT} (e.g. docker compose up backend).`,
  );
})();
