const fs = require('fs');
const http = require('http');
const path = require('path');

const PORTS = [8000, 8001];
const ENV_PATH = path.join(__dirname, '..', 'frontend', '.env.local');

async function checkPort(port) {
  return new Promise((resolve) => {
    const req = http.get(`http://127.0.0.1:${port}/docs`, { timeout: 500 }, (res) => {
      resolve(true);
    });
    req.on('error', () => resolve(false));
    req.on('timeout', () => { req.destroy(); resolve(false); });
  });
}

(async () => {
  for (const port of PORTS) {
    if (await checkPort(port)) {
      const content = `# Auto-generated by detect-backend.js
NEXT_PUBLIC_API_URL=http://localhost:${port}
CHAT_BACKEND_URL=http://localhost:${port}/api/v1/chat
TTS_BACKEND_URL=http://localhost:${port}/api/v1/tts-with-timing
`;
      fs.writeFileSync(ENV_PATH, content, { flag: 'a' });
      console.log(`✅ Backend detected on port ${port}, .env.local updated.`);
      return;
    }
  }
  console.log('❌ No backend found on ports 8000 or 8001. Using fallback (mock mode).');
})();
